### ISSUE TITLE
Add "None" option for the "Cookie Policy Link" (in the options area of the cookie manager) and don't show the link in the banner when "None" is selected

### ISSUE THREAD

**Issue by bembelimen** [joomla-projects/gsoc21_cookie-manager#16]
In progress by @shazmasiddiqui

Deadline: May, xxth EOD

- [ ] Clone this repo
- [ ] Create a branch based on the "final-cookie-manager" branch in your repo
- [ ] Commit your code to your branch
- [ ] Create a pull request (PR)
- [ ] Link the PR here
- [ ] Communicate the PR in the GLIP channel

**Comment by shazmasiddiqui** [comment]
Please test #18

**Comment by shazmasiddiqui** [comment]
Please test #20
