### ISSUE TITLE
4.2 ??

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc21_cookie-manager#36]
Do you still intend that this will be in j4.2? There is a LOT of work to be done. As a beta has now been released as feature complete can it really go into 4.2

**Comment by brianteeman** [comment]
As well as the issues already listed this really should not be dependent on bootstrap in the frontend

**Comment by bembelimen** [comment]
@roland-d or @fancyFranci

**Comment by brianteeman** [comment]
I spent some time reviewing the todo list and I added 20 more https://github.com/joomla-projects/gsoc21_cookie-manager/issues/14#issuecomment-1151636628

**Comment by roland-d** [comment]
The cookie manager will not be included in Joomla 4.2, it is not production ready. So let's give them more time to work on this feature as I do believe in the basis it is useful for the CMS it should be in a complete state or at least close to it.

**Comment by brianteeman** [comment]
When there are already great free extensions available I wouldnt suggest any more time was spent on this

Take a look at https://n3t-cookie-consent.readthedocs.io/en/latest/

A lightweight & gdpr compliant cookie consent solution for Joomla

n3t Cookie Consent manager for [Joomla! CMS](https://www.joomla.org/) based on [Orestbida Cookie Consent](https://github.com/orestbida/cookieconsent) javascript solution.

This is out of box solution for Joomla! CMS, providing:


- Highly customizable Cookie Consent dialog
- Automatic detection of new Cookies and its
- Automatic cookies description based on [Open Cookie Database](https://github.com/jkwakman/Open-Cookie-Database)
- multi lingual support
- multi site / domain support
- block storing of any JavaScript Cookie until consent (but not blocking scripts itself, like Google Analytics, Google Tag Manager etc.)
- Logging of user consents
- ...and more
